// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  getApiKeyConfig,
  getActiveKey,
  createRotationAwareFetch,
  clearKeyCache,
} from '@/lib/api-key-rotation';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Variáveis de ambiente Supabase não configuradas');
}

// ✅ API Key Rotation: resolve chave ativa (primária ou fallback)
const apiKeyConfig = getApiKeyConfig();
const activeKey = getActiveKey(apiKeyConfig);
const rotationFetch = apiKeyConfig.fallbackKey
  ? createRotationAwareFetch(apiKeyConfig)
  : undefined;

// Criar storage customizado com suporte a SSR
const createBrowserStorage = () => ({
  getItem: (key: string) => {
    if (typeof window === 'undefined') return null;
    return window.localStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    if (typeof window === 'undefined') return;
    window.localStorage.removeItem(key);
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  activeKey, 
  {
    auth: {
      storage: typeof window !== 'undefined' ? createBrowserStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      // ✅ PKCE flow (mais seguro)
      flowType: 'pkce',
    },
    // ✅ API Key Rotation: fetch wrapper com fallback automático
    global: {
      fetch: rotationFetch ?? fetch,
    },
  }
);

// ✅ Listener para expiração de sessão + limpeza de cache de rotação
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT' || event === 'TOKEN_REFRESHED') {
    if (event === 'SIGNED_OUT') {
      localStorage.removeItem('sensitive_data');
      clearKeyCache(); // Limpa cache de chave ativa ao fazer logout
    }
  }
});